--Up
ALTER TABLE Board ADD COLUMN refId INTEGER;
ALTER TABLE Board ADD COLUMN ceId INTEGER;

ALTER TABLE BoardColumn ADD COLUMN refId INTEGER;
ALTER TABLE BoardColumnCard ADD COLUMN refId INTEGER;
-- Down
