export default [
    {
        id: 'name',
        fieldtype: 'input',
        name: 'Name',
        placeholder: 'Eg, Fishtail Engineering College',
        required: true,
    },
    {
        id: 'headLine',
        fieldtype: 'input',
        name: 'Headline',
        placeholder: '.....',
    },
    {
        id: 'image',
        fieldtype: 'image',
        name: 'Emblem',
        placeholder: '',
        // required: true,
    },
    {
        id: 'address',
        fieldtype: 'input',
        name: 'Address',
        placeholder: 'Kathmandu, Nepal',
        required: true,
    },
    {
        id: 'phoneNo',
        fieldtype: 'input',
        name: 'Phone Number',
        specialType: 'mobile',
        placeholder: '+14 123 5489',
        required: true,
    },
    {
        id: 'email',
        fieldtype: 'input',
        specialType: 'email',
        name: 'Email',
        placeholder: 'test@support.com',
        required: true,
    },
    {
        id: 'webSiteUrl',
        fieldtype: 'input',
        name: 'Website',
        specialType: 'url',
        placeholder: 'Eg, https://www.properclass.com',
        required: true,
    },
    {
        id: 'submit',
        fieldtype: 'button',
        text: 'Submit',
        type: 'submit',
        fill: 'fill',
        intent: 'primary',
        large: 'large',
    },
];
