-- Up

CREATE TABLE IF NOT EXISTS Blog(
  id INTEGER PRIMARY KEY,
  userId INTEGER NOT NULL,
  timeStamp INTEGER NOT NULL,
  saveStatus TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BlogDetail(
  id INTEGER PRIMARY KEY,
  blogId INTEGER NOT NULL,
  blogHeader TEXT NOT NULL,
  blogContent TEXT NOT NULL,

  --CONSTRAINT
  CONSTRAINT BlogDetail_fk_blogId FOREIGN KEY (blogId) REFERENCES Blog(id)
);

CREATE TABLE IF NOT EXISTS Bloglike(
  id INTEGER PRIMARY KEY,
  blogId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  likeType text,
  timeStamp INTEGER NOT NULL,

  --CONSTRAINT
  CONSTRAINT BlogLike_fk_blogId FOREIGN KEY (blogId) REFERENCES Blog(id),
  CONSTRAINT BlogLike_fk_userId FOREIGN KEY (userId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS BlogComment(
  id INTEGER PRIMARY KEY,
  userId INTEGER NOT NULL,
  comment TEXT NOT NULL,
  timeStamp INTEGER NOT NULL,
  blogId INTEGER NOT NULL,

  --CONSTRAINT
  CONSTRAINT BlogComment_fk_userId FOREIGN KEY (userId) REFERENCES User(id),
  CONSTRAINT BlogComment_fk_blogId FOREIGN KEY (blogId) REFERENCES Blog(id)
);
-- Down
