export default [
  {
    id: 'firstName',
    fieldtype: 'input',
    name: 'First Name',
    placeholder: '',
    required: true,
  },
  {
    id: 'middleName',
    fieldtype: 'input',
    name: 'Middle Name',
    placeholder: '',
  },
  {
    id: 'lastName',
    fieldtype: 'input',
    name: 'Last Name',
    placeholder: '',
    required: true,
  },
  {
    id: 'email',
    fieldtype: 'input',
    name: 'Email',
    specialType: 'email',
    placeholder: 'Eg, alex@gmail.com',
    required: true,
  },
  {
    id: 'password',
    fieldtype: 'input',
    hidden: true,
    name: 'Password',
    placeholder: 'Eg, Xyz@123peQ',
    icon: {
      side: 'right',
      name: 'eye-open',
    },
    required: true,
  },
  {
    id: 'confirmPassword',
    fieldtype: 'input',
    hidden: true,
    name: 'Confirm Password',
    placeholder: 'Eg, ........',
    icon: {
      side: 'right',
      name: 'eye-open',
    },
    required: true,
  },
  {
    id: 'submit',
    fieldtype: 'button',
    type: 'submit',
    text: 'Submit',
    fill: 'fill',
    intent: 'primary',
    large: 'large',
  },
];
